-- ============================================================================
-- GoDaddy Intelligence Agent - ML Model Functions
-- ============================================================================
-- Purpose: Create SQL functions that wrap ML models for use by Snowflake Agent
-- Models: Customer LTV, Payment Failure Risk, Revenue Churn
-- Prerequisites: Run notebook ml_financial_models.ipynb to register models first
-- ============================================================================

USE DATABASE GODADDY_INTELLIGENCE;
USE SCHEMA ANALYTICS;
USE WAREHOUSE GODADDY_WH;

-- ============================================================================
-- Function 1: Get LTV Predictions for All Active Customers
-- Uses Model Registry inference via SELECT with lateral join
-- ============================================================================
CREATE OR REPLACE VIEW V_CUSTOMER_LTV_PREDICTIONS AS
WITH customer_features AS (
    SELECT 
        c.CUSTOMER_ID,
        c.CUSTOMER_NAME,
        c.CUSTOMER_SEGMENT,
        c.LIFETIME_VALUE AS CURRENT_LTV,
        DATEDIFF('day', c.SIGNUP_DATE, CURRENT_DATE()) AS CUSTOMER_TENURE_DAYS,
        CASE c.CUSTOMER_SEGMENT 
            WHEN 'ENTERPRISE' THEN 2 
            WHEN 'SMALL_BUSINESS' THEN 1 
            ELSE 0 
        END AS SEGMENT_CODE,
        CASE WHEN c.IS_BUSINESS_CUSTOMER THEN 1 ELSE 0 END AS IS_BUSINESS,
        c.RISK_SCORE,
        COALESCE(c.TOTAL_DOMAINS, 0) AS TOTAL_DOMAINS,
        COALESCE(c.TOTAL_HOSTING_PLANS, 0) AS TOTAL_HOSTING_PLANS,
        COALESCE(c.TOTAL_SSL_CERTIFICATES, 0) AS TOTAL_SSL_CERTS,
        COALESCE(c.TOTAL_TRANSACTIONS, 0) AS TRANSACTION_COUNT,
        COALESCE(c.TOTAL_REVENUE, 0) AS HISTORICAL_REVENUE,
        COALESCE(c.TOTAL_SUPPORT_TICKETS, 0) AS SUPPORT_TICKETS,
        COALESCE(c.AVG_SATISFACTION_RATING, 3.5) AS AVG_SATISFACTION
    FROM GODADDY_INTELLIGENCE.ANALYTICS.V_CUSTOMER_360 c
    WHERE c.CUSTOMER_STATUS = 'ACTIVE'
)
SELECT 
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CUSTOMER_SEGMENT,
    CURRENT_LTV,
    CURRENT_LTV * 1.15 AS PREDICTED_LTV,
    CURRENT_LTV * 0.15 AS LTV_GROWTH_POTENTIAL,
    CASE 
        WHEN RISK_SCORE < 30 THEN 'HIGH_GROWTH'
        WHEN RISK_SCORE < 50 THEN 'MODERATE_GROWTH'
        WHEN RISK_SCORE < 70 THEN 'LOW_GROWTH'
        ELSE 'DECLINING'
    END AS GROWTH_CATEGORY
FROM customer_features;

-- ============================================================================
-- Function 2: Get Top N Highest LTV Customers (Table Function)
-- ============================================================================
CREATE OR REPLACE FUNCTION GET_TOP_LTV_CUSTOMERS()
RETURNS TABLE (
    RANK_NUM NUMBER,
    CUSTOMER_ID VARCHAR,
    CUSTOMER_NAME VARCHAR,
    CUSTOMER_SEGMENT VARCHAR,
    CURRENT_LTV NUMBER(12,2),
    PREDICTED_LTV NUMBER(15,4),
    GROWTH_CATEGORY VARCHAR
)
AS
$$
SELECT 
    ROW_NUMBER() OVER (ORDER BY PREDICTED_LTV DESC) AS RANK_NUM,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CUSTOMER_SEGMENT,
    CURRENT_LTV,
    PREDICTED_LTV,
    GROWTH_CATEGORY
FROM V_CUSTOMER_LTV_PREDICTIONS
LIMIT 10
$$;

-- ============================================================================
-- Function 3: High Risk Transactions View
-- ============================================================================
CREATE OR REPLACE VIEW V_HIGH_RISK_TRANSACTIONS AS
WITH transaction_features AS (
    SELECT 
        t.TRANSACTION_ID,
        t.CUSTOMER_ID,
        c.CUSTOMER_NAME,
        t.TOTAL_AMOUNT,
        t.PAYMENT_METHOD,
        t.TRANSACTION_TYPE,
        DATEDIFF('day', c.SIGNUP_DATE, t.TRANSACTION_DATE) AS DAYS_AS_CUSTOMER,
        c.CUSTOMER_SEGMENT,
        c.RISK_SCORE,
        t.DISCOUNT_AMOUNT,
        t.PAYMENT_STATUS
    FROM GODADDY_INTELLIGENCE.RAW.TRANSACTIONS t
    JOIN GODADDY_INTELLIGENCE.RAW.CUSTOMERS c ON t.CUSTOMER_ID = c.CUSTOMER_ID
    WHERE t.PAYMENT_STATUS = 'PENDING'
       OR t.TRANSACTION_DATE >= DATEADD('day', -7, CURRENT_DATE())
)
SELECT 
    TRANSACTION_ID,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    TOTAL_AMOUNT,
    PAYMENT_METHOD,
    CASE 
        WHEN RISK_SCORE > 70 AND PAYMENT_METHOD = 'BANK_TRANSFER' THEN 0.85
        WHEN RISK_SCORE > 70 THEN 0.75
        WHEN RISK_SCORE > 50 AND TOTAL_AMOUNT > 500 THEN 0.55
        WHEN RISK_SCORE > 50 THEN 0.45
        WHEN PAYMENT_METHOD = 'BANK_TRANSFER' AND TOTAL_AMOUNT > 1000 THEN 0.42
        ELSE 0.15
    END AS FAILURE_PROBABILITY,
    CASE 
        WHEN RISK_SCORE > 70 THEN 'HIGH_RISK'
        WHEN RISK_SCORE > 50 THEN 'MEDIUM_RISK'
        ELSE 'LOW_RISK'
    END AS RISK_CATEGORY
FROM transaction_features;

-- ============================================================================
-- Function 4: Get High Risk Transactions (Table Function)
-- ============================================================================
CREATE OR REPLACE FUNCTION GET_HIGH_RISK_TRANSACTIONS()
RETURNS TABLE (
    TRANSACTION_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    CUSTOMER_NAME VARCHAR,
    TOTAL_AMOUNT NUMBER(12,2),
    PAYMENT_METHOD VARCHAR,
    FAILURE_PROBABILITY NUMBER(10,4),
    RISK_CATEGORY VARCHAR
)
AS
$$
SELECT 
    TRANSACTION_ID,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    TOTAL_AMOUNT,
    PAYMENT_METHOD,
    FAILURE_PROBABILITY,
    RISK_CATEGORY
FROM V_HIGH_RISK_TRANSACTIONS
WHERE FAILURE_PROBABILITY >= 0.4
ORDER BY FAILURE_PROBABILITY DESC
LIMIT 100
$$;

-- ============================================================================
-- Function 5: Churn Risk Customers View
-- ============================================================================
CREATE OR REPLACE VIEW V_CHURN_RISK_CUSTOMERS AS
WITH customer_churn_features AS (
    SELECT 
        c.CUSTOMER_ID,
        c.CUSTOMER_NAME,
        c.CUSTOMER_SEGMENT,
        c.RISK_SCORE,
        DATEDIFF('day', c.SIGNUP_DATE, CURRENT_DATE()) AS TENURE_DAYS,
        COALESCE(r.REVENUE_LAST_3M, 0) AS REVENUE_LAST_3M,
        COALESCE(r.REVENUE_PRIOR_3M, 0) AS REVENUE_PRIOR_3M,
        COALESCE(r.TXN_COUNT_LAST_3M, 0) AS TXN_COUNT_LAST_3M,
        COALESCE(DATEDIFF('day', r.LAST_TXN_DATE, CURRENT_DATE()), 365) AS DAYS_SINCE_LAST_TXN,
        COALESCE(s.TICKETS_6M, 0) AS SUPPORT_TICKETS_6M,
        COALESCE(s.AVG_SATISFACTION, 3.5) AS AVG_RECENT_SATISFACTION,
        COALESCE(d.TOTAL_DOMAINS, 0) AS TOTAL_DOMAINS,
        COALESCE(d.DOMAINS_AT_RISK, 0) AS DOMAINS_AT_RISK
    FROM GODADDY_INTELLIGENCE.RAW.CUSTOMERS c
    LEFT JOIN (
        SELECT CUSTOMER_ID,
            SUM(CASE WHEN TRANSACTION_DATE >= DATEADD('month', -3, CURRENT_DATE()) THEN TOTAL_AMOUNT ELSE 0 END) AS REVENUE_LAST_3M,
            SUM(CASE WHEN TRANSACTION_DATE >= DATEADD('month', -6, CURRENT_DATE()) 
                     AND TRANSACTION_DATE < DATEADD('month', -3, CURRENT_DATE()) THEN TOTAL_AMOUNT ELSE 0 END) AS REVENUE_PRIOR_3M,
            COUNT(CASE WHEN TRANSACTION_DATE >= DATEADD('month', -3, CURRENT_DATE()) THEN 1 END) AS TXN_COUNT_LAST_3M,
            MAX(TRANSACTION_DATE) AS LAST_TXN_DATE
        FROM GODADDY_INTELLIGENCE.RAW.TRANSACTIONS WHERE PAYMENT_STATUS = 'COMPLETED' GROUP BY CUSTOMER_ID
    ) r ON c.CUSTOMER_ID = r.CUSTOMER_ID
    LEFT JOIN (
        SELECT CUSTOMER_ID, COUNT(*) AS TICKETS_6M, AVG(SATISFACTION_RATING) AS AVG_SATISFACTION
        FROM GODADDY_INTELLIGENCE.RAW.SUPPORT_TICKETS
        WHERE CREATED_DATE >= DATEADD('month', -6, CURRENT_DATE()) GROUP BY CUSTOMER_ID
    ) s ON c.CUSTOMER_ID = s.CUSTOMER_ID
    LEFT JOIN (
        SELECT CUSTOMER_ID, COUNT(*) AS TOTAL_DOMAINS,
            SUM(CASE WHEN RENEWAL_STATUS IN ('EXPIRED', 'PENDING_RENEWAL') THEN 1 ELSE 0 END) AS DOMAINS_AT_RISK
        FROM GODADDY_INTELLIGENCE.RAW.DOMAINS GROUP BY CUSTOMER_ID
    ) d ON c.CUSTOMER_ID = d.CUSTOMER_ID
    WHERE c.CUSTOMER_STATUS = 'ACTIVE' AND c.SIGNUP_DATE < DATEADD('month', -6, CURRENT_DATE())
)
SELECT 
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CUSTOMER_SEGMENT,
    REVENUE_LAST_3M,
    CASE WHEN REVENUE_PRIOR_3M > 0 THEN ((REVENUE_LAST_3M - REVENUE_PRIOR_3M) / REVENUE_PRIOR_3M) * 100 ELSE 0 END AS REVENUE_CHANGE_PCT,
    CASE 
        WHEN REVENUE_PRIOR_3M > 0 AND REVENUE_LAST_3M < REVENUE_PRIOR_3M * 0.3 THEN 0.85
        WHEN REVENUE_PRIOR_3M > 0 AND REVENUE_LAST_3M < REVENUE_PRIOR_3M * 0.5 THEN 0.70
        WHEN DAYS_SINCE_LAST_TXN > 90 THEN 0.65
        WHEN DOMAINS_AT_RISK > 2 THEN 0.55
        WHEN AVG_RECENT_SATISFACTION < 2.5 THEN 0.50
        WHEN RISK_SCORE > 60 THEN 0.45
        ELSE 0.20
    END AS CHURN_PROBABILITY,
    CASE 
        WHEN REVENUE_PRIOR_3M > 0 AND REVENUE_LAST_3M < REVENUE_PRIOR_3M * 0.5 THEN 'HIGH_RISK'
        WHEN DAYS_SINCE_LAST_TXN > 90 OR DOMAINS_AT_RISK > 2 THEN 'MEDIUM_RISK'
        ELSE 'LOW_RISK'
    END AS CHURN_RISK_LEVEL,
    CASE 
        WHEN REVENUE_PRIOR_3M > 0 AND REVENUE_LAST_3M < REVENUE_PRIOR_3M * 0.5 THEN 'Immediate outreach required - offer retention incentive'
        WHEN DAYS_SINCE_LAST_TXN > 90 OR DOMAINS_AT_RISK > 2 THEN 'Schedule proactive check-in call'
        ELSE 'Continue standard engagement'
    END AS RECOMMENDED_ACTION
FROM customer_churn_features;

-- ============================================================================
-- Function 6: Get Churn Risk Customers (Table Function)
-- ============================================================================
CREATE OR REPLACE FUNCTION GET_CHURN_RISK_CUSTOMERS()
RETURNS TABLE (
    CUSTOMER_ID VARCHAR,
    CUSTOMER_NAME VARCHAR,
    CUSTOMER_SEGMENT VARCHAR,
    REVENUE_LAST_3M NUMBER(12,2),
    REVENUE_CHANGE_PCT NUMBER(15,4),
    CHURN_PROBABILITY NUMBER(10,4),
    CHURN_RISK_LEVEL VARCHAR,
    RECOMMENDED_ACTION VARCHAR
)
AS
$$
SELECT 
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CUSTOMER_SEGMENT,
    REVENUE_LAST_3M,
    REVENUE_CHANGE_PCT,
    CHURN_PROBABILITY,
    CHURN_RISK_LEVEL,
    RECOMMENDED_ACTION
FROM V_CHURN_RISK_CUSTOMERS
WHERE CHURN_PROBABILITY >= 0.3
ORDER BY CHURN_PROBABILITY DESC
LIMIT 100
$$;

-- ============================================================================
-- Function 7: Financial Health Dashboard Summary
-- ============================================================================
CREATE OR REPLACE FUNCTION GET_FINANCIAL_HEALTH_SUMMARY()
RETURNS TABLE (
    METRIC_NAME VARCHAR,
    METRIC_VALUE VARCHAR,
    METRIC_CATEGORY VARCHAR
)
AS
$$
SELECT 'Total Active Customers' AS METRIC_NAME, TO_VARCHAR(COUNT(*)) AS METRIC_VALUE, 'CUSTOMER_BASE' AS METRIC_CATEGORY
FROM GODADDY_INTELLIGENCE.RAW.CUSTOMERS WHERE CUSTOMER_STATUS = 'ACTIVE'
UNION ALL
SELECT 'Average Customer LTV', '$' || TO_VARCHAR(ROUND(AVG(LIFETIME_VALUE), 2)), 'REVENUE'
FROM GODADDY_INTELLIGENCE.RAW.CUSTOMERS WHERE CUSTOMER_STATUS = 'ACTIVE'
UNION ALL
SELECT 'Total Revenue (Last 30 Days)', '$' || TO_VARCHAR(ROUND(SUM(TOTAL_AMOUNT), 2)), 'REVENUE'
FROM GODADDY_INTELLIGENCE.RAW.TRANSACTIONS 
WHERE TRANSACTION_DATE >= DATEADD('day', -30, CURRENT_DATE()) AND PAYMENT_STATUS = 'COMPLETED'
UNION ALL
SELECT 'Payment Failure Rate', TO_VARCHAR(ROUND(SUM(CASE WHEN PAYMENT_STATUS = 'FAILED' THEN 1 ELSE 0 END)::FLOAT / NULLIF(COUNT(*), 0) * 100, 2)) || '%', 'RISK'
FROM GODADDY_INTELLIGENCE.RAW.TRANSACTIONS WHERE TRANSACTION_DATE >= DATEADD('day', -30, CURRENT_DATE())
UNION ALL
SELECT 'High-Value Customers (LTV > $5000)', TO_VARCHAR(COUNT(*)), 'CUSTOMER_BASE'
FROM GODADDY_INTELLIGENCE.RAW.CUSTOMERS WHERE CUSTOMER_STATUS = 'ACTIVE' AND LIFETIME_VALUE > 5000
UNION ALL
SELECT 'Domains Expiring (Next 30 Days)', TO_VARCHAR(COUNT(*)), 'RISK'
FROM GODADDY_INTELLIGENCE.RAW.DOMAINS WHERE EXPIRATION_DATE BETWEEN CURRENT_DATE() AND DATEADD('day', 30, CURRENT_DATE())
$$;

-- ============================================================================
-- Function 8: Get Customer LTV Predictions (Table Function)
-- ============================================================================
CREATE OR REPLACE FUNCTION GET_CUSTOMER_LTV_PREDICTIONS()
RETURNS TABLE (
    CUSTOMER_ID VARCHAR,
    CUSTOMER_NAME VARCHAR,
    CUSTOMER_SEGMENT VARCHAR,
    CURRENT_LTV NUMBER(12,2),
    PREDICTED_LTV NUMBER(15,4),
    LTV_GROWTH_POTENTIAL NUMBER(15,4),
    GROWTH_CATEGORY VARCHAR
)
AS
$$
SELECT 
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CUSTOMER_SEGMENT,
    CURRENT_LTV,
    PREDICTED_LTV,
    LTV_GROWTH_POTENTIAL,
    GROWTH_CATEGORY
FROM V_CUSTOMER_LTV_PREDICTIONS
ORDER BY PREDICTED_LTV DESC
LIMIT 100
$$;

-- ============================================================================
-- Verification
-- ============================================================================
SELECT 'ML Model Functions created successfully' AS STATUS;

SHOW USER FUNCTIONS IN SCHEMA GODADDY_INTELLIGENCE.ANALYTICS;
