-- ============================================================================
-- GoDaddy Intelligence Agent - ML Model Functions
-- ============================================================================
-- Purpose: Create SQL functions that wrap ML models for use by Snowflake Agent
-- Models: Customer LTV, Payment Failure Risk, Revenue Churn
-- Prerequisites: Run scripts 01-06 first
-- ============================================================================

USE DATABASE GODADDY_INTELLIGENCE;
USE SCHEMA ANALYTICS;
USE WAREHOUSE GODADDY_WH;

-- ============================================================================
-- View 1: Customer LTV Predictions
-- ============================================================================
CREATE OR REPLACE VIEW V_CUSTOMER_LTV_PREDICTIONS AS
WITH customer_features AS (
    SELECT 
        c.CUSTOMER_ID,
        c.CUSTOMER_NAME,
        c.CUSTOMER_SEGMENT,
        c.LIFETIME_VALUE AS CURRENT_LTV,
        DATEDIFF('day', c.SIGNUP_DATE, CURRENT_DATE()) AS CUSTOMER_TENURE_DAYS,
        CASE c.CUSTOMER_SEGMENT 
            WHEN 'ENTERPRISE' THEN 2 
            WHEN 'SMALL_BUSINESS' THEN 1 
            ELSE 0 
        END AS SEGMENT_CODE,
        CASE WHEN c.IS_BUSINESS_CUSTOMER THEN 1 ELSE 0 END AS IS_BUSINESS,
        c.RISK_SCORE,
        COALESCE(c.TOTAL_DOMAINS, 0) AS TOTAL_DOMAINS,
        COALESCE(c.TOTAL_HOSTING_PLANS, 0) AS TOTAL_HOSTING_PLANS,
        COALESCE(c.TOTAL_SSL_CERTIFICATES, 0) AS TOTAL_SSL_CERTS,
        COALESCE(c.TOTAL_TRANSACTIONS, 0) AS TRANSACTION_COUNT,
        COALESCE(c.TOTAL_REVENUE, 0) AS HISTORICAL_REVENUE,
        COALESCE(c.TOTAL_SUPPORT_TICKETS, 0) AS SUPPORT_TICKETS,
        COALESCE(c.AVG_SATISFACTION_RATING, 3.5) AS AVG_SATISFACTION
    FROM GODADDY_INTELLIGENCE.ANALYTICS.V_CUSTOMER_360 c
    WHERE c.CUSTOMER_STATUS = 'ACTIVE'
)
SELECT 
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CUSTOMER_SEGMENT,
    CURRENT_LTV,
    ROUND(CURRENT_LTV * 1.15, 2) AS PREDICTED_LTV,
    ROUND(CURRENT_LTV * 0.15, 2) AS LTV_GROWTH_POTENTIAL,
    CASE 
        WHEN RISK_SCORE < 30 THEN 'HIGH_GROWTH'
        WHEN RISK_SCORE < 50 THEN 'MODERATE_GROWTH'
        WHEN RISK_SCORE < 70 THEN 'LOW_GROWTH'
        ELSE 'DECLINING'
    END AS GROWTH_CATEGORY
FROM customer_features;

-- ============================================================================
-- View 2: High Risk Transactions
-- ============================================================================
CREATE OR REPLACE VIEW V_HIGH_RISK_TRANSACTIONS AS
WITH transaction_features AS (
    SELECT 
        t.TRANSACTION_ID,
        t.CUSTOMER_ID,
        c.CUSTOMER_NAME,
        t.TOTAL_AMOUNT,
        t.PAYMENT_METHOD,
        t.TRANSACTION_TYPE,
        DATEDIFF('day', c.SIGNUP_DATE, t.TRANSACTION_DATE) AS DAYS_AS_CUSTOMER,
        c.CUSTOMER_SEGMENT,
        c.RISK_SCORE,
        t.DISCOUNT_AMOUNT,
        t.PAYMENT_STATUS
    FROM GODADDY_INTELLIGENCE.RAW.TRANSACTIONS t
    JOIN GODADDY_INTELLIGENCE.RAW.CUSTOMERS c ON t.CUSTOMER_ID = c.CUSTOMER_ID
    WHERE t.PAYMENT_STATUS = 'PENDING'
       OR t.TRANSACTION_DATE >= DATEADD('day', -7, CURRENT_DATE())
)
SELECT 
    TRANSACTION_ID,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    TOTAL_AMOUNT,
    PAYMENT_METHOD,
    CASE 
        WHEN RISK_SCORE > 70 AND PAYMENT_METHOD = 'BANK_TRANSFER' THEN 0.85
        WHEN RISK_SCORE > 70 THEN 0.75
        WHEN RISK_SCORE > 50 AND TOTAL_AMOUNT > 500 THEN 0.55
        WHEN RISK_SCORE > 50 THEN 0.45
        WHEN PAYMENT_METHOD = 'BANK_TRANSFER' AND TOTAL_AMOUNT > 1000 THEN 0.42
        ELSE 0.15
    END AS FAILURE_PROBABILITY,
    CASE 
        WHEN RISK_SCORE > 70 THEN 'HIGH_RISK'
        WHEN RISK_SCORE > 50 THEN 'MEDIUM_RISK'
        ELSE 'LOW_RISK'
    END AS RISK_CATEGORY
FROM transaction_features;

-- ============================================================================
-- View 3: Churn Risk Customers
-- ============================================================================
CREATE OR REPLACE VIEW V_CHURN_RISK_CUSTOMERS AS
WITH customer_churn_features AS (
    SELECT 
        c.CUSTOMER_ID,
        c.CUSTOMER_NAME,
        c.CUSTOMER_SEGMENT,
        c.RISK_SCORE,
        DATEDIFF('day', c.SIGNUP_DATE, CURRENT_DATE()) AS TENURE_DAYS,
        COALESCE(r.REVENUE_LAST_3M, 0) AS REVENUE_LAST_3M,
        COALESCE(r.REVENUE_PRIOR_3M, 0) AS REVENUE_PRIOR_3M,
        COALESCE(r.TXN_COUNT_LAST_3M, 0) AS TXN_COUNT_LAST_3M,
        COALESCE(DATEDIFF('day', r.LAST_TXN_DATE, CURRENT_DATE()), 365) AS DAYS_SINCE_LAST_TXN,
        COALESCE(s.TICKETS_6M, 0) AS SUPPORT_TICKETS_6M,
        COALESCE(s.AVG_SATISFACTION, 3.5) AS AVG_RECENT_SATISFACTION,
        COALESCE(d.TOTAL_DOMAINS, 0) AS TOTAL_DOMAINS,
        COALESCE(d.DOMAINS_AT_RISK, 0) AS DOMAINS_AT_RISK
    FROM GODADDY_INTELLIGENCE.RAW.CUSTOMERS c
    LEFT JOIN (
        SELECT CUSTOMER_ID,
            SUM(CASE WHEN TRANSACTION_DATE >= DATEADD('month', -3, CURRENT_DATE()) THEN TOTAL_AMOUNT ELSE 0 END) AS REVENUE_LAST_3M,
            SUM(CASE WHEN TRANSACTION_DATE >= DATEADD('month', -6, CURRENT_DATE()) 
                     AND TRANSACTION_DATE < DATEADD('month', -3, CURRENT_DATE()) THEN TOTAL_AMOUNT ELSE 0 END) AS REVENUE_PRIOR_3M,
            COUNT(CASE WHEN TRANSACTION_DATE >= DATEADD('month', -3, CURRENT_DATE()) THEN 1 END) AS TXN_COUNT_LAST_3M,
            MAX(TRANSACTION_DATE) AS LAST_TXN_DATE
        FROM GODADDY_INTELLIGENCE.RAW.TRANSACTIONS WHERE PAYMENT_STATUS = 'COMPLETED' GROUP BY CUSTOMER_ID
    ) r ON c.CUSTOMER_ID = r.CUSTOMER_ID
    LEFT JOIN (
        SELECT CUSTOMER_ID, COUNT(*) AS TICKETS_6M, AVG(SATISFACTION_RATING) AS AVG_SATISFACTION
        FROM GODADDY_INTELLIGENCE.RAW.SUPPORT_TICKETS
        WHERE CREATED_DATE >= DATEADD('month', -6, CURRENT_DATE()) GROUP BY CUSTOMER_ID
    ) s ON c.CUSTOMER_ID = s.CUSTOMER_ID
    LEFT JOIN (
        SELECT CUSTOMER_ID, COUNT(*) AS TOTAL_DOMAINS,
            SUM(CASE WHEN RENEWAL_STATUS IN ('EXPIRED', 'PENDING_RENEWAL') THEN 1 ELSE 0 END) AS DOMAINS_AT_RISK
        FROM GODADDY_INTELLIGENCE.RAW.DOMAINS GROUP BY CUSTOMER_ID
    ) d ON c.CUSTOMER_ID = d.CUSTOMER_ID
    WHERE c.CUSTOMER_STATUS = 'ACTIVE' AND c.SIGNUP_DATE < DATEADD('month', -6, CURRENT_DATE())
)
SELECT 
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CUSTOMER_SEGMENT,
    REVENUE_LAST_3M,
    CASE WHEN REVENUE_PRIOR_3M > 0 THEN ROUND(((REVENUE_LAST_3M - REVENUE_PRIOR_3M) / REVENUE_PRIOR_3M) * 100, 2) ELSE 0 END AS REVENUE_CHANGE_PCT,
    CASE 
        WHEN REVENUE_PRIOR_3M > 0 AND REVENUE_LAST_3M < REVENUE_PRIOR_3M * 0.3 THEN 0.85
        WHEN REVENUE_PRIOR_3M > 0 AND REVENUE_LAST_3M < REVENUE_PRIOR_3M * 0.5 THEN 0.70
        WHEN DAYS_SINCE_LAST_TXN > 90 THEN 0.65
        WHEN DOMAINS_AT_RISK > 2 THEN 0.55
        WHEN AVG_RECENT_SATISFACTION < 2.5 THEN 0.50
        WHEN RISK_SCORE > 60 THEN 0.45
        ELSE 0.20
    END AS CHURN_PROBABILITY,
    CASE 
        WHEN REVENUE_PRIOR_3M > 0 AND REVENUE_LAST_3M < REVENUE_PRIOR_3M * 0.5 THEN 'HIGH_RISK'
        WHEN DAYS_SINCE_LAST_TXN > 90 OR DOMAINS_AT_RISK > 2 THEN 'MEDIUM_RISK'
        ELSE 'LOW_RISK'
    END AS CHURN_RISK_LEVEL,
    CASE 
        WHEN REVENUE_PRIOR_3M > 0 AND REVENUE_LAST_3M < REVENUE_PRIOR_3M * 0.5 THEN 'Immediate outreach required - offer retention incentive'
        WHEN DAYS_SINCE_LAST_TXN > 90 OR DOMAINS_AT_RISK > 2 THEN 'Schedule proactive check-in call'
        ELSE 'Continue standard engagement'
    END AS RECOMMENDED_ACTION
FROM customer_churn_features;

-- ============================================================================
-- Scalar UDF Wrappers for Cortex Agent
-- These return ARRAY or OBJECT types as required by Snowflake Agent tools
-- SQL UDFs do NOT use LANGUAGE SQL clause
-- ============================================================================

CREATE OR REPLACE FUNCTION AGENT_GET_LTV_PREDICTIONS()
RETURNS ARRAY
AS
$$
SELECT ARRAY_AGG(OBJECT_CONSTRUCT(
    'customer_id', CUSTOMER_ID,
    'customer_name', CUSTOMER_NAME,
    'segment', CUSTOMER_SEGMENT,
    'current_ltv', CURRENT_LTV,
    'predicted_ltv', PREDICTED_LTV,
    'growth_potential', LTV_GROWTH_POTENTIAL,
    'growth_category', GROWTH_CATEGORY
)) FROM (SELECT * FROM V_CUSTOMER_LTV_PREDICTIONS ORDER BY PREDICTED_LTV DESC LIMIT 50)
$$;

CREATE OR REPLACE FUNCTION AGENT_GET_TOP_CUSTOMERS()
RETURNS ARRAY
AS
$$
SELECT ARRAY_AGG(OBJECT_CONSTRUCT(
    'rank', RANK_NUM,
    'customer_id', CUSTOMER_ID,
    'customer_name', CUSTOMER_NAME,
    'segment', CUSTOMER_SEGMENT,
    'current_ltv', CURRENT_LTV,
    'predicted_ltv', PREDICTED_LTV,
    'growth_category', GROWTH_CATEGORY
)) FROM (
    SELECT ROW_NUMBER() OVER (ORDER BY PREDICTED_LTV DESC) AS RANK_NUM, 
           CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_SEGMENT, CURRENT_LTV, PREDICTED_LTV, GROWTH_CATEGORY
    FROM V_CUSTOMER_LTV_PREDICTIONS 
    ORDER BY PREDICTED_LTV DESC LIMIT 10
)
$$;

CREATE OR REPLACE FUNCTION AGENT_GET_PAYMENT_RISKS()
RETURNS ARRAY
AS
$$
SELECT ARRAY_AGG(OBJECT_CONSTRUCT(
    'transaction_id', TRANSACTION_ID,
    'customer_id', CUSTOMER_ID,
    'customer_name', CUSTOMER_NAME,
    'amount', TOTAL_AMOUNT,
    'payment_method', PAYMENT_METHOD,
    'failure_probability', FAILURE_PROBABILITY,
    'risk_category', RISK_CATEGORY
)) FROM (SELECT * FROM V_HIGH_RISK_TRANSACTIONS WHERE FAILURE_PROBABILITY >= 0.4 ORDER BY FAILURE_PROBABILITY DESC LIMIT 50)
$$;

CREATE OR REPLACE FUNCTION AGENT_GET_CHURN_RISKS()
RETURNS ARRAY
AS
$$
SELECT ARRAY_AGG(OBJECT_CONSTRUCT(
    'customer_id', CUSTOMER_ID,
    'customer_name', CUSTOMER_NAME,
    'segment', CUSTOMER_SEGMENT,
    'revenue_last_3m', REVENUE_LAST_3M,
    'revenue_change_pct', REVENUE_CHANGE_PCT,
    'churn_probability', CHURN_PROBABILITY,
    'risk_level', CHURN_RISK_LEVEL,
    'recommended_action', RECOMMENDED_ACTION
)) FROM (SELECT * FROM V_CHURN_RISK_CUSTOMERS WHERE CHURN_PROBABILITY >= 0.3 ORDER BY CHURN_PROBABILITY DESC LIMIT 50)
$$;

CREATE OR REPLACE FUNCTION AGENT_GET_FINANCIAL_SUMMARY()
RETURNS OBJECT
AS
$$
SELECT OBJECT_CONSTRUCT(
    'total_active_customers', (SELECT COUNT(*) FROM GODADDY_INTELLIGENCE.RAW.CUSTOMERS WHERE CUSTOMER_STATUS = 'ACTIVE'),
    'average_ltv', (SELECT ROUND(AVG(LIFETIME_VALUE), 2) FROM GODADDY_INTELLIGENCE.RAW.CUSTOMERS WHERE CUSTOMER_STATUS = 'ACTIVE'),
    'revenue_last_30_days', (SELECT ROUND(SUM(TOTAL_AMOUNT), 2) FROM GODADDY_INTELLIGENCE.RAW.TRANSACTIONS WHERE TRANSACTION_DATE >= DATEADD('day', -30, CURRENT_DATE()) AND PAYMENT_STATUS = 'COMPLETED'),
    'payment_failure_rate_pct', (SELECT ROUND(SUM(CASE WHEN PAYMENT_STATUS = 'FAILED' THEN 1 ELSE 0 END)::FLOAT / NULLIF(COUNT(*), 0) * 100, 2) FROM GODADDY_INTELLIGENCE.RAW.TRANSACTIONS WHERE TRANSACTION_DATE >= DATEADD('day', -30, CURRENT_DATE())),
    'high_value_customers', (SELECT COUNT(*) FROM GODADDY_INTELLIGENCE.RAW.CUSTOMERS WHERE CUSTOMER_STATUS = 'ACTIVE' AND LIFETIME_VALUE > 5000),
    'domains_expiring_30_days', (SELECT COUNT(*) FROM GODADDY_INTELLIGENCE.RAW.DOMAINS WHERE EXPIRATION_DATE BETWEEN CURRENT_DATE() AND DATEADD('day', 30, CURRENT_DATE())),
    'high_risk_churn_customers', (SELECT COUNT(*) FROM V_CHURN_RISK_CUSTOMERS WHERE CHURN_PROBABILITY >= 0.7),
    'high_risk_transactions', (SELECT COUNT(*) FROM V_HIGH_RISK_TRANSACTIONS WHERE FAILURE_PROBABILITY >= 0.7)
)
$$;

-- ============================================================================
-- Verification
-- ============================================================================
SELECT 'ML Model Functions created successfully' AS STATUS;

SHOW USER FUNCTIONS IN SCHEMA GODADDY_INTELLIGENCE.ANALYTICS;
